demo4signInAuthentication:
  cookieMaxAgeHour: 12

logging:
  file: /path/to/log-directory/demo4signInAuthentication.log
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file=: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'